### PR TITLE
Allow to use multiple files or groups

### PR DESCRIPTION
**Pull request by rastyagaev**
Issue #61 
It replaces several PR's related to this issue.

### CODE REVIEW

**Comment by Oshuma** [comment]
Nice.

**Comment by nashbridges** [comment]
It seems the fix was [never released](https://rubygems.org/gems/uploadcare-rails/versions) on Rubygems.
Guys, could you please double check this?

**Comment by dmitry-mukhin** [comment]
@nashbridges I'll look into it, thanks.

**Comment by dmitry-mukhin** [comment]
@nashbridges it's done. thanks for bringing our attention to this.

**Pull request merged**
